# Generated by Django 3.1 on 2021-11-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20211117_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
