# Generated by Django 3.1 on 2021-11-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20211117_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='update_date',
        ),
    ]
