# Generated by Django 3.1 on 2021-11-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20211117_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
