# Generated by Django 3.1 on 2021-12-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_auto_20211209_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('', 'Выбор языка'), ('py', 'python'), ('js', 'javaScript'), ('cs', 'C#')], max_length=30),
        ),
    ]
